services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: abm_production
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  api_handler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/abm_production?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    entrypoint: ["sh", "-c", "/wait-for-service.sh postgres 5432 && /usr/local/bin/api"]

volumes:
  pgdata:
